### ISSUE TITLE
大神，我这个台式机不是i3的，能用这个吗？

### ISSUE THREAD

**Issue by ulpyuxa** [hid0/efi-oc-hackintosh-coffeelake-i3-9100f#1]
电脑型号               技嘉 H310M DS2 台式电脑
  操作系统               Windows 10 Enterprise 64位（Version 21H1 / DirectX 12）

  处理器                 英特尔 Pentium(奔腾) Gold G5400 @ 3.70GHz 双核
  主板                   技嘉 H310M DS2（H310 芯片组）
  显卡                   英特尔 UHD Graphics 610 ( 128 MB / 技嘉 )
  内存                   16 GB ( 金士顿 DDR4 2400MHz / 金士顿 DDR4 2666MHz )
  主硬盘                 金士顿 SA400S37120G ( 120 GB / 固态硬盘 )
  显示器                 飞利浦 PHLC155 PHL 243V7 ( 23.8 英寸  )
  声卡                   瑞昱 ALC887 @ 英特尔 High Definition Audio 控制器
  网卡                   瑞昱 RTL8168/8111/8112 Gigabit Ethernet Controller / 技嘉

**Comment by hid0** [comment]
我不知道 Pentium Gold
我建议使用 i 系列处理器，如 i3/i5/i7/i9
有关完整文档，请参阅 https://dortania.github.io/getting-started/

**Comment by ulpyuxa** [comment]
抽空试下，吃下螃蟹

**Comment by hid0** [comment]
I don't know what you're saying.
english please.
before I use google translate
